version: '3'
services:
    my_app:
    build:
        context: .
        dockerfile: docker/Dockerfile
    volumes:
        - ./my_app/share/logs:/share/logs
    ports:
        - "3000:3000"
    tty: true
